In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
x = np.round(10*np.random.randn(4,5), 0)

In [7]:
print(x)

[[ -8.  23.  10.  -5.  -3.]
 [  4.   9. -15.   5.   6.]
 [ 12.   2.  11.  12.  -4.]
 [ -0.   7.  -6.   3.   4.]]


## Slicing

In [8]:
le = list(range(1,10))

In [9]:
le

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
[1, "My name", 1.0]

[1, 'My name', 1.0]

In [11]:
(1, "My name", 1.0)

(1, 'My name', 1.0)

In [20]:
for i in range(len(le)):
    print(le[i])

1
2
3
4
5
6
7
8
9


In [18]:
le[-2:]

[8, 9]

### Slicing in basic Python

list_type[ *begin*: *end*)

In [19]:
len(le)

9

np_array[begin:end:step, begin:end:step, ...]

In [21]:
x

array([[ -8.,  23.,  10.,  -5.,  -3.],
       [  4.,   9., -15.,   5.,   6.],
       [ 12.,   2.,  11.,  12.,  -4.],
       [ -0.,   7.,  -6.,   3.,   4.]])

In [23]:
x[1 ,   4:2:-1]

array([6., 5.])