In [4]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

a = np.arange(0, 50, 5)
#a

In [ ]:
#retrieve a single elment from a using a numeric index:
#a[3]
#a[7]

In [ ]:
#Multiple elements? slice
#a[3:7]

In [ ]:
#Multiple elements from indexes that cannot be expressed using a slice? fancy indexing.
#a[[2,3,5,7]]

In [ ]:
#We could also use a NumPy array to do this, instead of a list:
#indexes = np.array([2,3,5,7])
#a[indexes]

In [ ]:
#Here's the cool thing, though: 
#We pass a sequence of integers
#Also we can pass a sequence of boolean values.
#This is known as a boolean index.
#a[[True, True, True, False, False, False, True, True, True, False]]

In [ ]:
#using a variable
#b = [True, True, True, False, False, False, True, True, True, False]
#a[b]

In [5]:
#And with a Pandas series:
#s = Series(a)
#s[[True, True, True, False, False, False, True, True, True, False]]b

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#Boolean values as an index on a NumPy array. True values are returned, False values are ignored.

#Operations on NumPy arrays are vectorized:
#a = np.arange(0, 50, 5) 

In [6]:
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
a + 1

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [ ]:
#a * 10

In [ ]:
#When we add 1 to our array, Python actually adds 1 to every element, returning a new NumPy array. 
#OR Multiply

In [ ]:
#What happens when we apply a test to our NumPy array? 
#a == 20

In [ ]:
#a < 20

In [ ]:
#a >= 20

In [ ]:
#Assign it to a variable:
#i = a>=20
#i

In [ ]:
#What if we apply i (our array of boolean values) to our NumPy array?
#a[i]

In [ ]:
#We have now selected all of those values of a that are >= 20.
#No reason to define a new variable.  We can do it all in a single line:
#a[a>=20]

In [ ]:
#Let's look at it again:

#Vectorized comparison on "a", looking for elements >= 20
#Returns an array of boolean values, of the same length as "a"
#Apply this boolean array as an index to "a"
#We get back a new NumPy array, whose values are those of "a" with values >= 20

In [ ]:
#Let's find all of the odd elements of "a".
#a%2

In [ ]:
#let's use that result as an index
#a[a%2]

In [ ]:
#not boolean values but integers

#the fix
#a%2 == 1

In [ ]:
#odd
#a[a%2 == 1]

In [ ]:
#if we want even:
#a[a%2 == 0]

In [9]:
#now lets combine some of these tests
# first some random numbers
a = np.random.randint(0, 100, 10)

In [ ]:
#less than 50
#b = a[a<50]

In [ ]:
#only the odd ones
#b[b%2 == 1]

In [ ]:
#Makes sense to use a boolean condition here. 
#a[a<50 and a%2 == 1]

In [ ]:
#oops

#There are two different problems here. 
#and
#a<50 and a%2 == 1

#Are both of these expressions true?
#Test of truth? It won't even try.

In [ ]:
#We'll use Python's bitwise operators
#a<50 & a%2 == 1
 

In [13]:
#Precedence of the operators
(a<50) & (a%2 == 1)

array([ True, False, False, False, False, False, False, False, False,  True], dtype=bool)

In [11]:
a

array([39, 32, 59, 34, 46, 76, 66, 80, 66, 19])

In [14]:
#Finally!
a[(a<50) & (a%2 == 1)]

array([39, 19])

In [ ]:
#Less than 20, and  greater than 80?
#a[(a<20) | (a>80)]

In [ ]:
#The ~ (not) operator
#a[a>50]

#a[~(a>50)]

In [ ]:
#Complex?? All odd numbers that are less than 20 or greater than 80:
#((a<20) | (a>80)) & (a%2 == 0)

#a[((a<20) | (a>80)) & (a%2 == 0)]

#Notice parentheses to force the grouping.

In [8]:
###########Assignment #############
a = np.random.randint(0, 100, 10)

a

array([50,  6, 68, 65, 83, 19, 49, 96, 75, 80])

In [ ]:
#odd and less than 50:
#(a<50) & (a%2 == 1)

#a[(a<50) & (a%2 == 1)]

In [ ]:
3More interesting is that you can use a boolean index to assign back to your NumPy array.

#a[(a<50) & (a%2 == 1)] = 999

#a

In [14]:
#The two elements of "a" that were both less than 50 and odd were replaced with the value 999.

#####
#Lets look for numbers than one standard deviation away from the mean:
#a = np.random.randint(0, 100, 10)

#a

In [15]:
#(a > a.mean() + a.std())

In [ ]:
#(a > a.mean() + a.std()) | (a < a.mean() - a.std())

In [ ]:
#a[(a > a.mean() + a.std()) | (a < a.mean() - a.std())]

In [ ]:
#Replace the elements that are more than a.mean() + a.std() with that value, 
#The same with less than a.mean() - a.std().

#a[(a > a.mean() + a.std()) | (a < a.mean() - a.std())]

In [ ]:
#m = a.mean()

In [ ]:
#std = a.std()

In [ ]:
#a < m-std

In [ ]:
#assignment
#a[a < m-std] = m-std

In [ ]:
#a[a > m+std] = m+std

In [ ]:
#a

In [ ]:
#We have removed (or flattened) the outliers.

In [ ]:
#Coersion
#a = np.random.randint(0, 100, 10)

#a

In [ ]:
#a[a<50] = 123.456

#a

In [ ]:
#integers all the way down baby.

In [15]:
import matplotlib.pyplot as plt

In [17]:
x = plt.imread("../../TDS_Image_Proj/Images/thefan2.jpg")

In [20]:
x.shape

(480, 480, 3)

In [21]:
x

array([[[106, 116, 118],
        [105, 115, 117],
        [106, 116, 118],
        ..., 
        [105, 119, 120],
        [109, 120, 122],
        [110, 120, 121]],

       [[105, 115, 117],
        [104, 114, 116],
        [106, 116, 118],
        ..., 
        [105, 119, 120],
        [106, 120, 121],
        [110, 121, 123]],

       [[106, 114, 117],
        [107, 115, 118],
        [107, 115, 118],
        ..., 
        [107, 118, 120],
        [105, 119, 120],
        [104, 120, 120]],

       ..., 
       [[ 97,  96,  94],
        [ 99,  98,  96],
        [ 98,  98,  96],
        ..., 
        [ 88,  92,  91],
        [ 89,  93,  92],
        [ 89,  93,  92]],

       [[ 98,  98,  96],
        [ 97,  97,  95],
        [ 99,  98,  96],
        ..., 
        [ 87,  91,  90],
        [ 87,  91,  90],
        [ 89,  93,  94]],

       [[ 95,  97,  94],
        [ 98,  98,  96],
        [ 98,  97,  95],
        ..., 
        [ 85,  89,  88],
        [ 83,  87,  88],
        [ 87,  88,